### ISSUE TITLE
README

### ISSUE THREAD

**Issue by miiuzu** [Tacogamerman/Website-translator#1]
Hey! so i've tried this out and it's still the same even though I followed the instructions and everything!! um it shows this translate page but still is blocked! if you could help me on this that would be appreciated ~

**Comment by Tacogamerman** [comment]
Hello friend, thank you for this comment. I have been notified that it is broken,
And I recommend this unblocker. It is much stronger and better than my script.
Here is the link: 

https://github.com/dragon731012/-WORKING-bookmarklets-and-games/blob/main/school/single-script%20website%20proxy

Have a wonderful day my friend, Stay positive!
